## Parte 1: Análise Exploratória dos Dados (EDA)

In [63]:
# importando bibliotecas
import pandas as pd 
import matplotlib.pyplot as plt 

# lendo a base de dados
database = pd.read_csv("klike_challenge_dataset.csv")
database.head()

,campaign_id,date,platform,category,objective,target_audience_age,is_retargeting,video_duration_s,format,has_subtitle,...,clicks,ctr,cpc,spend,conversions,revenue,roas,avg_watch_time_s,engagement_rate,klike_score
0,KLK-0001,2024-01-01,Meta,Branding,awareness,18-24,False,NaN,vertical,True,...,5882,0.0390,0.82,4823.24,48,0.00,0.00,3.9,0.0446,63.6
1,KLK-0002,2024-03-22,LinkedIn,App Install,traffic,25-34,False,NaN,horizontal,True,...,493,0.0664,3.54,1745.22,34,NaN,0.16,6.4,0.0217,70.0
2,KLK-0003,2024-05-04,TikTok,SaaS,traffic,25-34,False,8.0,vertical,True,...,15069,0.0780,0.38,5726.22,492,51053.44,8.92,8.0,0.1000,99.1
3,KLK-0004,2024-12-27,TikTok,Lead Gen,engagement,25-34,False,27.0,quadrado,False,...,601,0.0925,0.71,426.71,19,1113.78,2.61,20.3,0.0414,74.9
4,KLK-0005,2024-07-10,Meta,Branding,engagement,25-34,False,34.0,vertical,True,...,2355,0.0369,0.38,894.90,13,0.00,0.00,34.0,0.0184,77.9

### Primeira Etapa: Consistência e Integridade dos Dados

In [62]:
# Verificando os dados Nan/Nulos de cada variável
table_nan_null = database.isna().sum()
table_nan_null.sort_values(ascending=False)

table_output = pd.DataFrame(table_nan_null)
table_output.columns = ["variavel"]
table_output


# CONCLUSÃO: para as colunas -> 
# "video_duration_s", "has_subtitle", "music_voice_ratio", "cpc", "revenue", "avg_watch_time_s" e "engagement_rate" 
# existem valores ausentes, e uma média de

                     variavel
campaign_id                 0
date                        0
platform                    0
category                    0
objective                   0
target_audience_age         0
is_retargeting              0
video_duration_s           39
format                      0
has_subtitle               46
has_cta                     0
has_hook                    0
has_face                    0
text_density                0
music_voice_ratio          38
impressions                 0
clicks                      0
ctr                         0
cpc                        28
spend                       0
conversions                 0
revenue                    25
roas                        0
avg_watch_time_s           27
engagement_rate            32
klike_score                 0

In [ ]:
informacoes = database.info()
# OBSERVAÇÕES: 
    # "date" está no formato de String. Seria melhor se estivesse em "datetime" direto
    # "has_subtitle" está com tipo "object". Entretanto, só pode assumir valores como verdadeiro e falso. Logo, deveria estar em "bool"